apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo2.fullname" . }}
  labels:
    {{- include "demo2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: 30036
      #targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo2.selectorLabels" . | nindent 4 }}
